export const routerAbi = [
  {
    inputs: [
      { internalType: 'address', name: 'asset_', type: 'address' },
      { internalType: 'uint256', name: 'assets_', type: 'uint256' },
      { internalType: 'uint128', name: 'callbackFee_', type: 'uint128' },
    ],
    name: 'quoteDeposit',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'asset_', type: 'address' },
      { internalType: 'uint256', name: 'shares_', type: 'uint256' },
      { internalType: 'uint128', name: 'callbackFee_', type: 'uint128' },
      { internalType: 'bool', name: 'isInstant_', type: 'bool' },
    ],
    name: 'quoteRedeem',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'asset_', type: 'address' },
      { internalType: 'uint256', name: 'assets_', type: 'uint256' },
      { internalType: 'uint256', name: 'sharesOutMin_', type: 'uint256' },
      { internalType: 'address', name: 'receiver_', type: 'address' },
      { internalType: 'address', name: 'operator_', type: 'address' },
      { internalType: 'bool', name: 'automatic_', type: 'bool' },
      { internalType: 'uint128', name: 'callbackFee_', type: 'uint128' },
    ],
    name: 'requestDeposit',
    outputs: [{ internalType: 'uint256', name: 'requestId_', type: 'uint256' }],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'asset_', type: 'address' },
      { internalType: 'uint256', name: 'shares_', type: 'uint256' },
      { internalType: 'uint256', name: 'assetsOutMin_', type: 'uint256' },
      { internalType: 'address', name: 'receiver_', type: 'address' },
      { internalType: 'address', name: 'operator_', type: 'address' },
      { internalType: 'bool', name: 'automatic_', type: 'bool' },
      { internalType: 'uint128', name: 'callbackFee_', type: 'uint128' },
      { internalType: 'bool', name: 'isInstant_', type: 'bool' },
    ],
    name: 'requestRedeem',
    outputs: [{ internalType: 'uint256', name: 'requestId_', type: 'uint256' }],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'requestId_', type: 'uint256' }],
    name: 'claimDeposit',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'requestId_', type: 'uint256' }],
    name: 'claimRedeem',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'requestId_', type: 'uint256' }],
    name: 'recoverDeposit',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'requestId_', type: 'uint256' }],
    name: 'recoverRedeem',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'requestId_', type: 'uint256' }],
    name: 'cancel',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'asset', type: 'address' }],
    name: 'assetsData',
    outputs: [
      {
        components: [
          { internalType: 'address', name: 'share', type: 'address' },
          { internalType: 'address', name: 'remoteAsset', type: 'address' },
          { internalType: 'address', name: 'remoteShare', type: 'address' },
          { internalType: 'bool', name: 'enabled', type: 'bool' },
        ],
        internalType: 'struct Router.AssetData',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'requestId_', type: 'uint256' }],
    name: 'requests',
    outputs: [
      {
        components: [
          { internalType: 'uint8', name: 'kind', type: 'uint8' },
          { internalType: 'address', name: 'asset', type: 'address' },
          { internalType: 'address', name: 'share', type: 'address' },
          { internalType: 'uint256', name: 'assets', type: 'uint256' },
          { internalType: 'uint256', name: 'shares', type: 'uint256' },
          { internalType: 'uint256', name: 'amountOutMin', type: 'uint256' },
          { internalType: 'address', name: 'operator', type: 'address' },
          { internalType: 'address', name: 'receiver', type: 'address' },
          { internalType: 'bool', name: 'automatic', type: 'bool' },
          { internalType: 'uint8', name: 'status', type: 'uint8' },
        ],
        internalType: 'struct Router.Request',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'nextRequestId',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'uint256',
        name: 'requestId',
        type: 'uint256',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'asset',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'assets',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'amountOutMin',
        type: 'uint256',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'receiver',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'bool',
        name: 'automatic',
        type: 'bool',
      },
    ],
    name: 'DepositRequested',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'uint256',
        name: 'requestId',
        type: 'uint256',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'asset',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'shares',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'amountOutMin',
        type: 'uint256',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'receiver',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'bool',
        name: 'automatic',
        type: 'bool',
      },
    ],
    name: 'RedeemRequested',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'uint256',
        name: 'requestId',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'amount',
        type: 'uint256',
      },
    ],
    name: 'RequestFulfilled',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'uint256',
        name: 'requestId',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'amount',
        type: 'uint256',
      },
    ],
    name: 'RequestCancelled',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'uint256',
        name: 'requestId',
        type: 'uint256',
      },
    ],
    name: 'RequestClaimed',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'uint256',
        name: 'requestId',
        type: 'uint256',
      },
    ],
    name: 'RequestRecovered',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'uint256',
        name: 'requestId',
        type: 'uint256',
      },
    ],
    name: 'CancellationRequested',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint256',
        name: 'requestId',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'bytes',
        name: 'reason',
        type: 'bytes',
      },
    ],
    name: 'AutoFinalizationFailed',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'asset',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'share',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'remoteAsset',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'remoteShare',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'bool',
        name: 'enabled',
        type: 'bool',
      },
    ],
    name: 'AssetDataUpdated',
    type: 'event',
  },
  {
    inputs: [],
    name: 'peerAddress',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    stateMutability: 'view',
    type: 'function',
  },
] as const
