'use client'

import * as Sentry from '@sentry/nextjs'
import { ExclamationMark } from 'components/icons/exclamationMark'
import hemiSocials from 'hemi-socials'
import Image from 'next/image'
import { useEffect } from 'react'

import Error500 from './_images/500.svg'

const { discordUrl } = hemiSocials

// This file is not statically generated by next. Even though I import the styles
// they don't seem to load. It seems to be a bug in Next.js.
// See https://github.com/vercel/next.js/issues/70553
// Apparently, it's been fixed in Next 15, but next15 does not work yet for us
// TODO see https://github.com/hemilabs/ui-monorepo/issues/1093
export default function GlobalError({
  error,
}: {
  error: Error & { digest?: string }
}) {
  useEffect(
    function () {
      Sentry.captureException(error)
    },
    [error],
  )

  return (
    // At this point of the route, we can't determine which language we're in
    // let's default to English
    <html lang="en">
      <head>
        <title>Hemi Portal</title>
        <link href="/favicon.ico" rel="icon" />
        <link href="https://fonts.googleapis.com" rel="preconnect" />
        <link href="https://fonts.gstatic.com" rel="preconnect" />
        <link rel="stylesheet" />
        {/* Next does not load tailwind nor imports .css files
        So we need to manually add the styles needed here. */}
        <style>{`
          .-top-15 { top: -60px; }
          .-z-10 { z-index: -10; }
          .absolute { position: absolute; }
          .flex { display: flex; }
          .flex-col { flex-direction: column; }
          .font-medium { font-weight: 500; }
          .gap-4 { gap: 1rem; }
          .h-full { height: 100%; }
          .h-screen { height: 100dvh; }
          .inset-0 { inset: 0; }
          .inter-font {
            font-family: "Inter", sans-serif;
            font-optical-sizing: auto;
            font-weight: 500;
            font-style: normal;
          }
          .items-center { align-items: center; }
          .justify-center: { justify-content: center; }
          .m-0 { margin: 0; }
          .m-auto { margin: auto; }
          .mt-1 { margin-top: 0.25rem; }
          .primary-button {
            background-image: linear-gradient(to bottom, #FF6C15, #F04D06);
            border-radius: 0.5rem;
            box-sizing: content-box;
            color: #FFF;
            cursor: pointer;
            font-size: 0.875rem;
            border: 1px solid rgb(199 56 7 / 0.55);
            padding: 0.375rem 0.75rem;
            transition-property: all;
            transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
            transition-duration: 150ms;
          }
          .primary-button:hover {
            background-image: linear-gradient(to bottom, #F04D06, #F04D06);
            border-color: rgba(199, 56, 7, 0.7);
          }
          .text-base { font-size: 1rem; letter-spacing: -0.32px;  line-height: 24px; }
          .text-center { text-align: center; }
          .text-lg { font-size: 1.125rem; letter-spacing: -0.36px; line-height: 24px; }
          .text-neutral-500 { color: #737373; }
          .text-neutral-950 { color:  #0A0A0A; }
          .text-orange-500 { color: #FF6C15; }
          .text-orange-500:hover { color: #C73807; }
          .w-96 { width: 24rem; }
          .w-full { width: 100%; }
        `}</style>
      </head>
      <body className="inter-font m-0 h-screen">
        <div className="flex h-full">
          <Image
            alt="500"
            className="-top-15 absolute inset-0 -z-10 m-auto w-full"
            src={Error500}
          />
          <div className="m-auto flex flex-col items-center gap-4">
            <ExclamationMark />
            <div className="w-96 text-center">
              <h1 className="text-lg font-medium">Something Went Wrong</h1>
              <h3 className="mt-1 text-base font-medium text-neutral-500">
                An unexpected error has occurred. Please try again or
                <a className="text-orange-500" href={discordUrl}>
                  {' '}
                  contact us{' '}
                </a>
                if the problem persists.
              </h3>
            </div>
            <button
              className="primary-button flex items-center justify-center font-medium"
              onClick={() => window.location.replace('/')}
            >
              Try again
            </button>
          </div>
        </div>
      </body>
    </html>
  )
}
