'use client'

import { Error500 } from 'components/error500'
import hemiSocials from 'hemi-socials'
import { type ComponentProps } from 'react'

const { discordUrl } = hemiSocials

// This file is not statically generated by next. Even though I import the styles
// they don't seem to load. It seems to be a bug in Next.js.
// See https://github.com/vercel/next.js/issues/70553
// Apparently, it's been fixed in Next 15, but next15 does not work yet for us
// TODO see https://github.com/hemilabs/ui-monorepo/issues/1093
const GlobalError = (props: Pick<ComponentProps<typeof Error500>, 'error'>) => (
  // At this point of the route, we can't determine which language we're in
  // let's default to English
  <html lang="en">
    <head>
      <title>Hemi Portal</title>
      <link href="/favicon.ico" rel="icon" />
      <link href="https://fonts.googleapis.com" rel="preconnect" />
      <link href="https://fonts.gstatic.com" rel="preconnect" />
      <link rel="stylesheet" />
      {/* Next does not load tailwind nor imports .css files
        So we need to manually add the styles needed here. */}
      <style>{`
          .-top-15 { top: -60px; }
          .-z-10 { z-index: -10; }
          .absolute { position: absolute; }
          .flex { display: flex; }
          .flex-col { flex-direction: column; }
          .font-medium { font-weight: 500; }
          .gap-4 { gap: 1rem; }
          .h-full { height: 100%; }
          .h-screen { height: 100dvh; }
          .inset-0 { inset: 0; }
          .inter-font {
            font-family: "Inter", sans-serif;
            font-optical-sizing: auto;
            font-weight: 500;
            font-style: normal;
          }
          .items-center { align-items: center; }
          .justify-center: { justify-content: center; }
          .m-0 { margin: 0; }
          .m-auto { margin: auto; }
          .mt-1 { margin-top: 0.25rem; }
          .primary-button {
            background-image: linear-gradient(to bottom, #FF6C15, #F04D06);
            border-radius: 0.5rem;
            box-sizing: content-box;
            color: #FFF;
            cursor: pointer;
            font-size: 0.875rem;
            border: 1px solid rgb(199 56 7 / 0.55);
            padding: 0.375rem 0.75rem;
            transition-property: all;
            transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
            transition-duration: 150ms;
          }
          .primary-button:hover {
            background-image: linear-gradient(to bottom, #F04D06, #F04D06);
            border-color: rgba(199, 56, 7, 0.7);
          }
          .text-base { font-size: 1rem; letter-spacing: -0.32px;  line-height: 24px; }
          .text-center { text-align: center; }
          .text-lg { font-size: 1.125rem; letter-spacing: -0.36px; line-height: 24px; }
          .text-neutral-500 { color: #737373; }
          .text-neutral-950 { color:  #0A0A0A; }
          .text-orange-500 { color: #FF6C15; }
          .text-orange-500:hover { color: #C73807; }
          .w-96 { width: 24rem; }
          .w-full { width: 100%; }
        `}</style>
    </head>
    <body className="inter-font m-0 h-screen">
      <Error500
        {...props}
        // I couldn't find a way to read these from the translation files,
        // so I had to hardcode them :/
        description={
          <>
            An unexpected error has occurred. Please try again or
            <a
              className="text-orange-500 hover:text-orange-700"
              href={discordUrl}
            >
              {' '}
              contact us{' '}
            </a>
            if the problem persists.
          </>
        }
        reset={() => window.location.replace('/')}
        title="Something Went Wrong"
        tryAgainLabel="Try again"
      />
    </body>
  </html>
)

export default GlobalError
