name: Deploy Portal

description: Deploys the portal to Hostinger

inputs:
  HOSTINGER_HOST:
    required: true
    description: Hostinger host
  HOSTINGER_PORT:
    required: true
    description: Hostinger port
  HOSTINGER_SSH_KEY:
    required: true
    description: Hostinger SSH key
  HOSTINGER_USER:
    required: true
    description: Hostinger user
  HOSTINGER_TARGET:
    required: true
    description: Hostinger target
  NEXT_PUBLIC_ANALYTICS_URL:
    required: false
    description: Analytics URL
  NEXT_PUBLIC_ANALYTICS_WEBSITE_ID:
    required: false
    description: Analytics website ID
  NEXT_PUBLIC_BITCOIN_PAST_VAULTS_MAINNET:
    required: false
    description: Comma-separated list of past bitcoin vault indexes for Mainnet
  NEXT_PUBLIC_BITCOIN_PAST_VAULTS_SEPOLIA:
    required: false
    description: Comma-separated list of past bitcoin vault indexes for Sepolia
  NEXT_PUBLIC_COOKIE3_SITE_ID:
    required: false
    description: Cookie3 site ID
  NEXT_PUBLIC_CUSTOM_RPC_URL_HEMI_MAINNET:
    required: false
    description: Custom RPC URL for Hemi Mainnet
  NEXT_PUBLIC_CUSTOM_RPC_URL_HEMI_SEPOLIA:
    required: false
    description: Custom RPC URL for Hemi Sepolia
  NEXT_PUBLIC_CUSTOM_RPC_URL_MAINNET:
    required: false
    description: Custom RPC URL for Mainnet
  NEXT_PUBLIC_CUSTOM_RPC_URL_SEPOLIA:
    required: false
    description: Custom RPC URL for Sepolia
  NEXT_PUBLIC_DEFAULT_BITCOIN_VAULT_MAINNET:
    required: false
    description: Default Bitcoin vault index for Mainnet
  NEXT_PUBLIC_DEFAULT_BITCOIN_VAULT_SEPOLIA:
    required: false
    description: Default Bitcoin vault index for Sepolia
  NEXT_PUBLIC_ENABLE_ANALYTICS:
    required: false
    description: Flag to enable or not analytics
  NEXT_PUBLIC_ENABLE_BTC_YIELD_CLAIM_REWARDS:
    required: false
    description: Flag to enable or not BTC Yield claim rewards
  NEXT_PUBLIC_BTC_YIELD_OPPORTUNITY_ID:
    required: false
    description: Opportunity ID for BTC yield campaigns
  NEXT_PUBLIC_ENABLE_BTC_YIELD_PAGE:
    required: false
    description: Flag to enable or not the BTC Yield page
  NEXT_PUBLIC_ENABLE_BTC_YIELD_TESTNET:
    required: false
    description: Flag to enable or not BTC Yield on testnet
  NEXT_PUBLIC_ENABLE_COOKIE3:
    required: false
    description: Flag to enable or not Cookie3
  NEXT_PUBLIC_ENABLE_CLAIM_REWARDS_TESTNET:
    required: false
    description: Flag to enable or not claim rewards on testnet
  NEXT_PUBLIC_ENABLE_STAKE_GOVERNANCE_TESTNET:
    required: false
    description: Flag to enable or not stake governance on testnet
  NEXT_PUBLIC_ENABLE_STAKE_TESTNET:
    required: false
    description: Flag to enable or not stake on testnet
  NEXT_PUBLIC_PORTAL_API_URL:
    required: true
    description: Portal API URL to get token prices, user points, TVL and more
  NEXT_PUBLIC_SENTRY_DSN:
    required: false
    description: Sentry DSN URL
  NEXT_PUBLIC_SUBGRAPHS_API_URL:
    required: false
    description: Subgraphs API URL
  NEXT_PUBLIC_TRACES_SAMPLE_RATE:
    required: false
    description: Sentry traces sample rate
  NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID:
    required: false
    description: Wallet Connect project ID
  SENTRY_AUTH_TOKEN:
    required: false
    description: Sentry auth token
  SENTRY_ENVIRONMENT:
    required: false
    description: Sentry environment
  SENTRY_ORG:
    required: false
    description: Sentry organization
  SENTRY_PROJECT:
    required: false
    description: Sentry project
  SENTRY_RELEASE:
    required: false
    description: Sentry Release version

runs:
  using: composite
  steps:
    - run: npx lerna run deploy --scope=portal
      shell: bash
      name: Build site
      env:
        NEXT_PUBLIC_ANALYTICS_URL: ${{ inputs.NEXT_PUBLIC_ANALYTICS_URL }}
        NEXT_PUBLIC_ANALYTICS_WEBSITE_ID: ${{ inputs.NEXT_PUBLIC_ANALYTICS_WEBSITE_ID }}
        NEXT_PUBLIC_COOKIE3_SITE_ID: ${{ inputs.NEXT_PUBLIC_COOKIE3_SITE_ID }}
        NEXT_PUBLIC_BITCOIN_PAST_VAULTS_MAINNET: ${{ inputs.NEXT_PUBLIC_BITCOIN_PAST_VAULTS_MAINNET }}
        NEXT_PUBLIC_BITCOIN_PAST_VAULTS_SEPOLIA: ${{ inputs.NEXT_PUBLIC_BITCOIN_PAST_VAULTS_SEPOLIA }}
        NEXT_PUBLIC_CUSTOM_RPC_URL_HEMI_MAINNET: ${{ inputs.NEXT_PUBLIC_CUSTOM_RPC_URL_HEMI_MAINNET }}
        NEXT_PUBLIC_CUSTOM_RPC_URL_HEMI_SEPOLIA: ${{ inputs.NEXT_PUBLIC_CUSTOM_RPC_URL_HEMI_SEPOLIA }}
        NEXT_PUBLIC_CUSTOM_RPC_URL_MAINNET: ${{ inputs.NEXT_PUBLIC_CUSTOM_RPC_URL_MAINNET }}
        NEXT_PUBLIC_CUSTOM_RPC_URL_SEPOLIA: ${{ inputs.NEXT_PUBLIC_CUSTOM_RPC_URL_SEPOLIA }}
        NEXT_PUBLIC_DEFAULT_BITCOIN_VAULT_MAINNET: ${{ inputs.NEXT_PUBLIC_DEFAULT_BITCOIN_VAULT_MAINNET }}
        NEXT_PUBLIC_DEFAULT_BITCOIN_VAULT_SEPOLIA: ${{ inputs.NEXT_PUBLIC_DEFAULT_BITCOIN_VAULT_SEPOLIA}}
        NEXT_PUBLIC_ENABLE_ANALYTICS: ${{ inputs.NEXT_PUBLIC_ENABLE_ANALYTICS }}
        NEXT_PUBLIC_ENABLE_BTC_YIELD_CLAIM_REWARDS: ${{ inputs.NEXT_PUBLIC_ENABLE_BTC_YIELD_CLAIM_REWARDS }}
        NEXT_PUBLIC_BTC_YIELD_OPPORTUNITY_ID: ${{ inputs.NEXT_PUBLIC_BTC_YIELD_OPPORTUNITY_ID }}
        NEXT_PUBLIC_ENABLE_BTC_YIELD_PAGE: ${{ inputs.NEXT_PUBLIC_ENABLE_BTC_YIELD_PAGE }}
        NEXT_PUBLIC_ENABLE_BTC_YIELD_TESTNET: ${{ inputs.NEXT_PUBLIC_ENABLE_BTC_YIELD_TESTNET }}
        NEXT_PUBLIC_ENABLE_COOKIE3: ${{ inputs.NEXT_PUBLIC_ENABLE_COOKIE3 }}
        NEXT_PUBLIC_ENABLE_CLAIM_REWARDS_TESTNET: ${{ inputs.NEXT_PUBLIC_ENABLE_CLAIM_REWARDS_TESTNET }}
        NEXT_PUBLIC_ENABLE_STAKE_GOVERNANCE_TESTNET: ${{ inputs.NEXT_PUBLIC_ENABLE_STAKE_GOVERNANCE_TESTNET }}
        NEXT_PUBLIC_ENABLE_STAKE_TESTNET: ${{ inputs.NEXT_PUBLIC_ENABLE_STAKE_TESTNET }}
        NEXT_PUBLIC_PORTAL_API_URL: ${{ inputs.NEXT_PUBLIC_PORTAL_API_URL }}
        NEXT_PUBLIC_SENTRY_DSN: ${{ inputs.NEXT_PUBLIC_SENTRY_DSN }}
        NEXT_PUBLIC_SUBGRAPHS_API_URL: ${{ inputs.NEXT_PUBLIC_SUBGRAPHS_API_URL }}
        NEXT_PUBLIC_TRACES_SAMPLE_RATE: ${{ inputs.NEXT_PUBLIC_TRACES_SAMPLE_RATE }}
        NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID: ${{ inputs.NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID }}
        SENTRY_AUTH_TOKEN: ${{ inputs.SENTRY_AUTH_TOKEN }}
        SENTRY_ENVIRONMENT: ${{ inputs.SENTRY_ENVIRONMENT }}
        SENTRY_ORG: ${{ inputs.SENTRY_ORG }}
        SENTRY_PROJECT: ${{ inputs.SENTRY_PROJECT }}
        SENTRY_RELEASE: ${{ inputs.SENTRY_RELEASE }}
    - name: Check portal build
      id: portal_build
      uses: andstor/file-existence-action@v3
      with:
        files: ./portal/out/
    # folder should only exist if portal was built
    - if: steps.portal_build.outputs.files_exists == 'true'
      name: Copy portal files to Hostinger
      uses: appleboy/scp-action@master
      with:
        host: ${{ inputs.HOSTINGER_HOST }}
        key: ${{ inputs.HOSTINGER_SSH_KEY }}
        port: ${{ inputs.HOSTINGER_PORT }}
        rm: true
        source: portal/out/*
        strip_components: 2
        target: ${{ inputs.HOSTINGER_TARGET }}
        username: ${{ inputs.HOSTINGER_USER }}
