name: Deploy Portal

description: Deploys the portal to Hostinger

inputs:
  HOSTINGER_HOST:
    required: true
    description: Hostinger host
  HOSTINGER_PORT:
    required: true
    description: Hostinger port
  HOSTINGER_SSH_KEY:
    required: true
    description: Hostinger SSH key
  HOSTINGER_USER:
    required: true
    description: Hostinger user
  HOSTINGER_TARGET:
    required: true
    description: Hostinger target
  NEXT_PUBLIC_ANALYTICS_URL:
    required: false
    description: Analytics URL
  NEXT_PUBLIC_ANALYTICS_WEBSITE_ID:
    required: false
    description: Analytics website ID
  NEXT_PUBLIC_CUSTOM_RPC_URL_HEMI_MAINNET:
    required: false
    description: Custom RPC URL for Hemi Mainnet
  NEXT_PUBLIC_CUSTOM_RPC_URL_HEMI_SEPOLIA:
    required: false
    description: Custom RPC URL for Hemi Sepolia
  NEXT_PUBLIC_CUSTOM_RPC_URL_MAINNET:
    required: false
    description: Custom RPC URL for Mainnet
  NEXT_PUBLIC_CUSTOM_RPC_URL_SEPOLIA:
    required: false
    description: Custom RPC URL for Sepolia
  NEXT_PUBLIC_DEFAULT_BITCOIN_VAULT_MAINNET:
    required: false
    description: Default Bitcoin vault index for Mainnet
  NEXT_PUBLIC_DEFAULT_BITCOIN_VAULT_SEPOLIA:
    required: false
    description: Default Bitcoin vault index for Sepolia
  NEXT_PUBLIC_ENABLE_ANALYTICS:
    required: false
    description: Flag to enable or not analytics
  NEXT_PUBLIC_ENABLE_STAKE_TESTNET:
    required: false
    description: Flag to enable or not stake on testnet
  NEXT_PUBLIC_FEATURE_FLAG_ENABLE_STAKE_CAMPAIGN:
    required: true
    description: Feature flag to enable Stake Campaign
  NEXT_PUBLIC_FEATURE_FLAG_SYNC_SUBGRAPH:
    required: false
    description: Feature flag to enable syncing the user history with Subgraphs
  NEXT_PUBLIC_FEATURE_FLAG_SYNC_WITHDRAWALS_SUBGRAPH:
    required: false
    description: Feature flag to enable syncing withdrawals with the Subgraph
  NEXT_PUBLIC_POINTS_URL:
    required: false
    description: Hemi Points URL
  NEXT_PUBLIC_TOKEN_PRICES_URL:
    required: false
    description: Token prices URL
  NEXT_PUBLIC_SENTRY_DSN:
    required: false
    description: Sentry DSN URL
  NEXT_PUBLIC_SUBGRAPH_API_KEY:
    required: false
    description: Subgraph API key
  NEXT_PUBLIC_SUBGRAPH_HEMI_URL:
    required: false
    description: Hemi subgraph URL
  NEXT_PUBLIC_SUBGRAPH_HEMI_SEPOLIA_URL:
    required: false
    description: Hemi Sepolia subgraph URL
  NEXT_PUBLIC_SUBGRAPH_HEMI_ID:
    required: false
    description: Hemi subgraph ID
  NEXT_PUBLIC_SUBGRAPH_HEMI_SEPOLIA_ID:
    required: false
    description: Hemi Sepolia subgraph ID
  NEXT_PUBLIC_SUBGRAPH_MAINNET_ID:
    required: false
    description: Mainnet subgraph ID
  NEXT_PUBLIC_SUBGRAPH_SEPOLIA_ID:
    required: false
    description: Sepolia subgraph ID
  NEXT_PUBLIC_SUBGRAPH_STAKE_HEMI_ID:
    required: false
    description: Hemi Stake subgraph ID
  NEXT_PUBLIC_SUBGRAPH_STAKE_HEMI_SEPOLIA_ID:
    required: false
    description: Hemi Sepolia Stake subgraph ID
  NEXT_PUBLIC_SUBGRAPH_STAKE_HEMI_URL:
    required: false
    description: Hemi Stake subgraph URL
  NEXT_PUBLIC_SUBGRAPH_STAKE_HEMI_SEPOLIA_URL:
    required: false
    description: Hemi Sepolia Stake subgraph URL
  NEXT_PUBLIC_SUBGRAPH_MAINNET_URL:
    required: false
    description: Mainnet subgraph URL
  NEXT_PUBLIC_SUBGRAPH_SEPOLIA_URL:
    required: false
    description: Sepolia Subgraph URL
  NEXT_PUBLIC_TRACES_SAMPLE_RATE:
    required: false
    description: Sentry traces sample rate
  SENTRY_AUTH_TOKEN:
    required: false
    description: Sentry auth token
  SENTRY_ENVIRONMENT:
    required: false
    description: Sentry environment
  SENTRY_ORG:
    required: false
    description: Sentry organization
  SENTRY_PROJECT:
    required: false
    description: Sentry project
  SENTRY_RELEASE:
    required: false
    description: Sentry Release version
  NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID:
    required: false
    description: Wallet Connect project ID

runs:
  using: composite
  steps:
    - run: npx lerna run deploy --scope=app
      shell: bash
      name: Build site
      env:
        NEXT_PUBLIC_ANALYTICS_URL: ${{ inputs.NEXT_PUBLIC_ANALYTICS_URL }}
        NEXT_PUBLIC_ANALYTICS_WEBSITE_ID: ${{ inputs.NEXT_PUBLIC_ANALYTICS_WEBSITE_ID }}
        NEXT_PUBLIC_CUSTOM_RPC_URL_HEMI_MAINNET: ${{ inputs.NEXT_PUBLIC_CUSTOM_RPC_URL_HEMI_MAINNET }}
        NEXT_PUBLIC_CUSTOM_RPC_URL_HEMI_SEPOLIA: ${{ inputs.NEXT_PUBLIC_CUSTOM_RPC_URL_HEMI_SEPOLIA }}
        NEXT_PUBLIC_CUSTOM_RPC_URL_MAINNET: ${{ inputs.NEXT_PUBLIC_CUSTOM_RPC_URL_MAINNET }}
        NEXT_PUBLIC_CUSTOM_RPC_URL_SEPOLIA: ${{ inputs.NEXT_PUBLIC_CUSTOM_RPC_URL_SEPOLIA }}
        NEXT_PUBLIC_DEFAULT_BITCOIN_VAULT_MAINNET: ${{ inputs.NEXT_PUBLIC_DEFAULT_BITCOIN_VAULT_MAINNET }}
        NEXT_PUBLIC_DEFAULT_BITCOIN_VAULT_SEPOLIA: ${{ inputs.NEXT_PUBLIC_DEFAULT_BITCOIN_VAULT_SEPOLIA}}
        NEXT_PUBLIC_ENABLE_ANALYTICS: ${{ inputs.NEXT_PUBLIC_ENABLE_ANALYTICS }}
        NEXT_PUBLIC_ENABLE_STAKE_TESTNET: ${{ inputs.NEXT_PUBLIC_ENABLE_STAKE_TESTNET }}
        NEXT_PUBLIC_FEATURE_FLAG_ENABLE_STAKE_CAMPAIGN: ${{ inputs.NEXT_PUBLIC_FEATURE_FLAG_ENABLE_STAKE_CAMPAIGN }}
        NEXT_PUBLIC_FEATURE_FLAG_SYNC_SUBGRAPH: ${{ inputs.NEXT_PUBLIC_FEATURE_FLAG_SYNC_SUBGRAPH }}
        NEXT_PUBLIC_FEATURE_FLAG_SYNC_WITHDRAWALS_SUBGRAPH: ${{ inputs.NEXT_PUBLIC_FEATURE_FLAG_SYNC_WITHDRAWALS_SUBGRAPH }}
        NEXT_PUBLIC_POINTS_URL: ${{ inputs.NEXT_PUBLIC_POINTS_URL }}
        NEXT_PUBLIC_TOKEN_PRICES_URL: ${{ inputs.NEXT_PUBLIC_TOKEN_PRICES_URL }}
        NEXT_PUBLIC_SENTRY_DSN: ${{ inputs.NEXT_PUBLIC_SENTRY_DSN }}
        NEXT_PUBLIC_SUBGRAPH_API_KEY: ${{ inputs.NEXT_PUBLIC_SUBGRAPH_API_KEY }}
        NEXT_PUBLIC_SUBGRAPH_HEMI_URL: ${{ inputs.NEXT_PUBLIC_SUBGRAPH_HEMI_URL }}
        NEXT_PUBLIC_SUBGRAPH_HEMI_SEPOLIA_URL: ${{ inputs.NEXT_PUBLIC_SUBGRAPH_HEMI_SEPOLIA_URL }}
        NEXT_PUBLIC_SUBGRAPH_HEMI_ID: ${{ inputs.NEXT_PUBLIC_SUBGRAPH_HEMI_ID }}
        NEXT_PUBLIC_SUBGRAPH_HEMI_SEPOLIA_ID: ${{ inputs.NEXT_PUBLIC_SUBGRAPH_HEMI_SEPOLIA_ID }}
        NEXT_PUBLIC_SUBGRAPH_MAINNET_ID: ${{ inputs.NEXT_PUBLIC_SUBGRAPH_MAINNET_ID }}
        NEXT_PUBLIC_SUBGRAPH_SEPOLIA_ID: ${{ inputs.NEXT_PUBLIC_SUBGRAPH_SEPOLIA_ID }}
        NEXT_PUBLIC_SUBGRAPH_STAKE_HEMI_ID: ${{ inputs.NEXT_PUBLIC_SUBGRAPH_STAKE_HEMI_ID }}
        NEXT_PUBLIC_SUBGRAPH_STAKE_HEMI_SEPOLIA_ID: ${{ inputs.NEXT_PUBLIC_SUBGRAPH_STAKE_HEMI_SEPOLIA_ID }}
        NEXT_PUBLIC_SUBGRAPH_STAKE_HEMI_URL: ${{ inputs.NEXT_PUBLIC_SUBGRAPH_STAKE_HEMI_URL }}
        NEXT_PUBLIC_SUBGRAPH_STAKE_HEMI_SEPOLIA_URL: ${{ inputs.NEXT_PUBLIC_SUBGRAPH_STAKE_HEMI_SEPOLIA_URL }}
        NEXT_PUBLIC_SUBGRAPH_MAINNET_URL: ${{ inputs.NEXT_PUBLIC_SUBGRAPH_MAINNET_URL }}
        NEXT_PUBLIC_SUBGRAPH_SEPOLIA_URL: ${{ inputs.NEXT_PUBLIC_SUBGRAPH_SEPOLIA_URL }}
        NEXT_PUBLIC_TRACES_SAMPLE_RATE: ${{ inputs.NEXT_PUBLIC_TRACES_SAMPLE_RATE }}
        SENTRY_AUTH_TOKEN: ${{ inputs.SENTRY_AUTH_TOKEN }}
        SENTRY_ENVIRONMENT: ${{ inputs.SENTRY_ENVIRONMENT }}
        SENTRY_ORG: ${{ inputs.SENTRY_ORG }}
        SENTRY_PROJECT: ${{ inputs.SENTRY_PROJECT }}
        SENTRY_RELEASE: ${{ inputs.SENTRY_RELEASE }}
        NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID: ${{ inputs.NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID }}
    - name: Check portal build
      id: portal_build
      uses: andstor/file-existence-action@v3
      with:
        files: ./webapp/out/
    # folder should only exist if portal was built
    - if: steps.portal_build.outputs.files_exists == 'true'
      name: Copy portal files to Hostinger
      uses: appleboy/scp-action@master
      with:
        host: ${{ inputs.HOSTINGER_HOST }}
        key: ${{ inputs.HOSTINGER_SSH_KEY }}
        port: ${{ inputs.HOSTINGER_PORT }}
        rm: true
        source: webapp/out/*
        strip_components: 2
        target: ${{ inputs.HOSTINGER_TARGET }}
        username: ${{ inputs.HOSTINGER_USER }}
