name: Deploy Portal

description: Deploys the portal to Hostinger

inputs:
  HOSTINGER_HOST:
    required: true
    description: Hostinger host
  HOSTINGER_PORT:
    required: true
    description: Hostinger port
  HOSTINGER_SSH_KEY:
    required: true
    description: Hostinger SSH key
  HOSTINGER_USER:
    required: true
    description: Hostinger user
  HOSTINGER_TARGET:
    required: true
    description: Hostinger target
  NEXT_PUBLIC_ANALYTICS_URL:
    required: false
    description: Analytics URL
  NEXT_PUBLIC_ANALYTICS_WEBSITE_ID:
    required: false
    description: Analytics website ID
  NEXT_PUBLIC_CUSTOM_RPC_URL_HEMI_MAINNET:
    required: false
    description: Custom RPC URL for Hemi Mainnet
  NEXT_PUBLIC_CUSTOM_RPC_URL_HEMI_SEPOLIA:
    required: false
    description: Custom RPC URL for Hemi Sepolia
  NEXT_PUBLIC_CUSTOM_RPC_URL_MAINNET:
    required: false
    description: Custom RPC URL for Mainnet
  NEXT_PUBLIC_CUSTOM_RPC_URL_SEPOLIA:
    required: false
    description: Custom RPC URL for Sepolia
  NEXT_PUBLIC_ENABLE_ANALYTICS:
    required: false
    description: Flag to enable or not analytics
  NEXT_PUBLIC_FEATURE_FLAG_ENABLE_BTC_TUNNEL:
    required: true
    description: Feature flag to enable BTC tunnel
  NEXT_PUBLIC_RELEASE_VERSION:
    required: false
    description: Release version
  NEXT_PUBLIC_SENTRY_DSN:
    required: false
    description: Sentry DSN URL
  NEXT_PUBLIC_SENTRY_ENVIRONMENT:
    required: false
    description: Sentry environment
  NEXT_PUBLIC_TRACES_SAMPLE_RATE:
    required: false
    description: Sentry traces sample rate
  SENTRY_AUTH_TOKEN:
    required: false
    description: Sentry auth token
  SENTRY_ORG:
    required: false
    description: Sentry organization
  SENTRY_PROJECT:
    required: false
    description: Sentry project

runs:
  using: composite
  steps:
    - run: npx lerna run deploy --scope=app
      shell: bash
      name: Build site
      env:
        NEXT_PUBLIC_ANALYTICS_URL: ${{ inputs.NEXT_PUBLIC_ANALYTICS_URL }}
        NEXT_PUBLIC_ANALYTICS_WEBSITE_ID: ${{ inputs.NEXT_PUBLIC_ANALYTICS_WEBSITE_ID }}
        NEXT_PUBLIC_CUSTOM_RPC_URL_HEMI_MAINNET: ${{ inputs.NEXT_PUBLIC_CUSTOM_RPC_URL_HEMI_MAINNET }}
        NEXT_PUBLIC_CUSTOM_RPC_URL_HEMI_SEPOLIA: ${{ inputs.NEXT_PUBLIC_CUSTOM_RPC_URL_HEMI_SEPOLIA }}
        NEXT_PUBLIC_CUSTOM_RPC_URL_MAINNET: ${{ inputs.NEXT_PUBLIC_CUSTOM_RPC_URL_MAINNET }}
        NEXT_PUBLIC_CUSTOM_RPC_URL_SEPOLIA: ${{ inputs.NEXT_PUBLIC_CUSTOM_RPC_URL_SEPOLIA }}
        NEXT_PUBLIC_ENABLE_ANALYTICS: ${{ inputs.NEXT_PUBLIC_ENABLE_ANALYTICS }}
        NEXT_PUBLIC_FEATURE_FLAG_ENABLE_BTC_TUNNEL: ${{ inputs.NEXT_PUBLIC_FEATURE_FLAG_ENABLE_BTC_TUNNEL }}
        NEXT_PUBLIC_RELEASE_VERSION: ${{ inputs.NEXT_PUBLIC_RELEASE_VERSION }}
        NEXT_PUBLIC_SENTRY_DSN: ${{ inputs.NEXT_PUBLIC_SENTRY_DSN }}
        NEXT_PUBLIC_SENTRY_ENVIRONMENT: ${{ inputs.NEXT_PUBLIC_SENTRY_ENVIRONMENT }}
        NEXT_PUBLIC_TRACES_SAMPLE_RATE: ${{ inputs.NEXT_PUBLIC_TRACES_SAMPLE_RATE }}
        SENTRY_AUTH_TOKEN: ${{ inputs.SENTRY_AUTH_TOKEN }}
        SENTRY_ORG: ${{ inputs.SENTRY_ORG }}
        SENTRY_PROJECT: ${{ inputs.SENTRY_PROJECT }}
    - name: Check portal build
      id: portal_build
      uses: andstor/file-existence-action@v3
      with:
        files: ./webapp/out/
    # folder should only exists if portal was built
    - if: steps.portal_build.outputs.files_exists == 'true'
      name: Copy portal files to Hostinger
      uses: appleboy/scp-action@master
      with:
        host: ${{ inputs.HOSTINGER_HOST }}
        key: ${{ inputs.HOSTINGER_SSH_KEY }}
        port: ${{ inputs.HOSTINGER_PORT }}
        rm: true
        source: webapp/out/*
        strip_components: 2
        target: ${{ inputs.HOSTINGER_TARGET }}
        username: ${{ inputs.HOSTINGER_USER }}
