name: Deploy portal
description: Deploys the portal to Hostinger

inputs:
  HOSTINGER_HOST:
    required: true
    description: 'Hostinger host'
  HOSTINGER_PORT:
    required: true
    description: 'Hostinger port'
  HOSTINGER_SSH_KEY:
    required: true
    description: 'Hostinger SSH key'
  HOSTINGER_USER:
    required: true
    description: 'Hostinger user'
  HOSTINGER_TARGET:
    required: true
    description: 'Hostinger target'
  NEXT_PUBLIC_CUSTOM_RPC_URL_HEMI_MAINNET:
    required: false
    description: 'Custom RPC URL for Hemi Mainnet'
  NEXT_PUBLIC_CUSTOM_RPC_URL_HEMI_SEPOLIA:
    required: false
    description: 'Custom RPC URL for Hemi Sepolia'
  NEXT_PUBLIC_CUSTOM_RPC_URL_MAINNET:
    required: false
    description: 'Custom RPC URL for Mainnet'
  NEXT_PUBLIC_CUSTOM_RPC_URL_SEPOLIA:
    required: false
    description: 'Custom RPC URL for Sepolia'
  NEXT_PUBLIC_FEATURE_FLAG_ENABLE_BTC_TUNNEL:
    required: true
    description: 'Feature flag to enable BTC tunnel'
  NEXT_PUBLIC_RECAPTCHA_SITE_KEY:
    required: true
    description: 'Recaptcha site key'
  NEXT_PUBLIC_CLAIM_TOKENS_URL:
    required: true
    description: 'Claim tokens microservice URL'

runs:
  using: composite
  steps:
    - name: Build site
      run: npx lerna run deploy --scope=app
      shell: bash
      env:
        NEXT_PUBLIC_CUSTOM_RPC_URL_HEMI_MAINNET: ${{ inputs.NEXT_PUBLIC_CUSTOM_RPC_URL_HEMI_MAINNET }}
        NEXT_PUBLIC_CUSTOM_RPC_URL_HEMI_SEPOLIA: ${{ inputs.NEXT_PUBLIC_CUSTOM_RPC_URL_HEMI_SEPOLIA }}
        NEXT_PUBLIC_CUSTOM_RPC_URL_MAINNET: ${{ inputs.NEXT_PUBLIC_CUSTOM_RPC_URL_MAINNET }}
        NEXT_PUBLIC_CUSTOM_RPC_URL_SEPOLIA: ${{ inputs.NEXT_PUBLIC_CUSTOM_RPC_URL_SEPOLIA }}
        NEXT_PUBLIC_FEATURE_FLAG_ENABLE_BTC_TUNNEL: ${{ inputs.NEXT_PUBLIC_FEATURE_FLAG_ENABLE_BTC_TUNNEL }}
        NEXT_PUBLIC_RECAPTCHA_SITE_KEY: ${{ inputs.NEXT_PUBLIC_RECAPTCHA_SITE_KEY }}
        NEXT_PUBLIC_CLAIM_TOKENS_URL: ${{ inputs.NEXT_PUBLIC_CLAIM_TOKENS_URL }}

    - name: Check portal build
      id: portal_build
      uses: andstor/file-existence-action@v3
      with:
        files: './webapp/out/'

    - name: Copy portal files to Hostinger
      # folder should only exists if portal was built
      if: steps.portal_build.outputs.files_exists == 'true'
      uses: appleboy/scp-action@master
      with:
        host: ${{ inputs.HOSTINGER_HOST }}
        username: ${{ inputs.HOSTINGER_USER }}
        port: ${{ inputs.HOSTINGER_PORT }}
        key: ${{ inputs.HOSTINGER_SSH_KEY }}
        source: webapp/out/*
        target: ${{ inputs.HOSTINGER_TARGET }}
        rm: true
        strip_components: 2
