services:
  api:
    build:
      context: api
    environment:
      CACHE_MINUTES: ${CACHE_MINUTES}
      CHAIN: ${CHAIN}
      NODE_ENV: production
      ORIGINS: ${ORIGINS}
      PORT: ${PORT:-3003}
    ports:
      - ${PORT:-3003}:${PORT:-3003}
  cron:
    build:
      context: cron
    environment:
      API_URL: http://api:${PORT:-3003}
      NODE_ENV: production
      REFRESH_INTERVAL_SEC: ${REFRESH_INTERVAL_SEC}
      SLACK_MENTION: ${SLACK_MENTION}
      SLACK_WEBHOOK_URL: ${SLACK_WEBHOOK_URL}
      SLEEP: 1
    depends_on:
      - api
