name: Docker Build and Push

description: Build and push Docker images

inputs:
  context:
    description: 'The build context'
    required: false
    default: '.'
  dockerHubPassword:
    description: 'Docker Hub token'
    required: true
  dockerHubUsername:
    description: 'Docker Hub username'
    required: true
  images:
    description: 'The Docker image name'
    required: true

runs:
  using: composite
  steps:
    - uses: docker/setup-buildx-action@v3
    - id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.images }}
<<<<<<< Updated upstream
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=ref,event=tag
          type=sha,prefix=
=======
>>>>>>> Stashed changes
    - uses: docker/login-action@v3
      with:
        password: ${{ inputs.dockerHubPassword }}
        username: ${{ inputs.dockerHubUsername }}
    - uses: docker/build-push-action@v6
      with:
        context: ${{ inputs.context }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64
<<<<<<< Updated upstream
        provenance: true
        push: true
        sbom: true
=======
        push: true
>>>>>>> Stashed changes
        tags: ${{ steps.meta.outputs.tags }}
