services:
  cache:
    image: redis:7.2.7-alpine
  cron:
    build:
      context: cron
    environment:
      CACHE_EXPIRATION_SEC: ${CACHE_EXPIRATION_SEC}
      COIN_MARKET_CAP_API_KEY: ${COIN_MARKET_CAP_API_KEY}
      COIN_MARKET_CAP_SLUGS: ${COIN_MARKET_CAP_SLUGS}
      NODE_ENV: production
      REDIS_URL: redis://cache:6379
      REFRESH_INTERVAL_SEC: ${REFRESH_INTERVAL_SEC}
    depends_on:
      - cache
  api:
    build:
      context: api
    environment:
      NODE_ENV: production
      ORIGINS: ${ORIGINS}
      PORT: ${PORT}
      REDIS_URL: redis://cache:6379
    depends_on:
      - cache
    ports:
      - 3000:3000
