name: Docker Checks

on:
  pull_request:
    paths:
      - 'portal-backend/**'
      - 'subgraph-api/**'
  push:
    paths:
      - 'portal-backend/**'
      - 'subgraph-api/**'

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  docker-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - run: docker build --tag ${{ matrix.image }}:local ${{ matrix.context }}
      - uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
      - uses: docker/scout-action@8910519cee8ac046f3ee99686b0dc6654d5ba1a7 # v1.20.3
        with:
          command: cves
          exit-code: true
          only-fixed: true
          only-severities: critical,high
          only-vex-affected: true
          image: ${{ matrix.image }}:local
    strategy:
      matrix:
        include:
          - context: portal-backend/api
            image: hemilabs/portal-backend-api
          - context: portal-backend/cron/hemi-supply
            image: hemilabs/hemi-supply-cron
          - context: portal-backend/cron/token-prices
            image: hemilabs/token-prices-cron
          - context: portal-backend/cron/vaults-monitor
            image: hemilabs/vaults-monitor-cron
          - context: subgraph-api
            image: hemilabs/subgraph-api
