name: JS Checks

on:
  pull_request:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  js-checks:
    uses: hemilabs/.github/.github/workflows/js-checks-pnpm.yml@e9f85a5eb81dda87d4c046eda82e45822bc1ee32
