name: JS Checks

on:
  pull_request:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  js-checks:
    uses: hemilabs/.github/.github/workflows/js-checks-pnpm.yml@c0d930f1959633dd7dc1203d95ec6634dbaf9a34 #v1.2.0
