name: Subgraphs Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'subgraphs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: false

jobs:
  deploy-subgraph:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - id: version-check
        run: |
          git fetch origin main
          PACKAGE_JSON_PATH="subgraphs/${{ matrix.subgraph }}/package.json"
          PREVIOUS_VERSION=$(git show origin/main^1:${PACKAGE_JSON_PATH} | jq -r .version 2>/dev/null || echo "none")
          CURRENT_VERSION=$(jq -r .version ${PACKAGE_JSON_PATH})
          if [ "$PREVIOUS_VERSION" = "none" ] || [ "$CURRENT_VERSION" != "$PREVIOUS_VERSION" ]; then
            echo "VERSION_CHANGED=true" >> $GITHUB_OUTPUT
          else
            echo "VERSION_CHANGED=false" >> $GITHUB_OUTPUT
          fi
      - if: steps.version-check.outputs.VERSION_CHANGED == 'true'
        uses: ./.github/actions/deploy-subgraph
        with:
          graph-api-key: ${{ secrets.GRAPH_API_KEY }}
          reference: ${{ github.event.head_commit.message }}
          slack-mention: ${{ vars.SLACK_MENTION }}
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          subgraph: ${{ matrix.subgraph }}
    strategy:
      matrix:
        subgraph:
          - hemi-stake-operations-subgraph
          - hemi-token-merkle-claims-subgraph
          - hemi-tunnel-btc-deposits-subgraph
          - hemi-tunnel-deposits-subgraph
          - hemi-tunnel-withdrawals-proof-claim-subgraph
          - hemi-tunnel-withdrawals-subgraph
          - ve-hemi-subgraph
